services:
  build-psycopg2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_VER=16.3
        - PSYCOPG_VER=2.9.9
    command: cp -r ./ /psycopg2-lambda/build
    volumes:
      - .:/psycopg2-lambda